export const GET_WORLD_DETAILS = 'GET_WORLD_DETAILS';
export const GET_WORLD_DETAILS_PROGRESS = 'GET_WORLD_DETAILS_PROGRESS';
export const GET_WORLD_DETAILS_SUCCESS = 'GET_WORLD_DETAILS_SUCCESS';
export const GET_WORLD_DETAILS_FAILURE = 'GET_WORLD_DETAILS_FAILURE';
export const REST_ALL_VALUE = 'REST_ALL_VALUE';
